language: cpp
sudo: required

compiler:
  - g++

before_install:
  - curl http://pkgconfig.freedesktop.org/releases/pkg-config-0.28.tar.gz -o pkgconfig.tgz
  - tar -zxf pkgconfig.tgz
  - cd pkg-config-0.28
  - ./configure --with-internal-glib 
  - sudo make install

script:
  - make test
